// ─────────────────────────────────────────────────────────
// FILE: core/engines/mellotron/mellotron_tables.h
// BRIEF: Mellotron wavetables — multi-cycle with per-cycle
//        timbral variation to simulate tape imperfections
// ─────────────────────────────────────────────────────────
#pragma once
#include "shared/types.h"
#include <array>
#include <cmath>

// ════════════════════════════════════════════════════════
// 4 tape types, each an 8-cycle wavetable at 2048 samples/cycle.
// Total: 16384 samples per tape.  8 cycles with per-cycle
// harmonic jitter + phase drift simulate tape loop character.
// Generated by build() — call once at startup.
// ════════════════════════════════════════════════════════

enum class MellotronTape : int {
    Strings = 0,   // detuned sawtooths (chorus effect)
    Choir   = 1,   // formant-shaped vowel wave
    Flute   = 2,   // sine + soft noise
    Brass   = 3,   // bright saw with odd harmonics
    COUNT   = 4
};

constexpr int MELLO_CYCLE_SIZE  = 2048;   // samples per cycle
constexpr int MELLO_CYCLES      = 8;      // cycles per tape loop
constexpr int MELLO_TABLE_SIZE  = MELLO_CYCLE_SIZE * MELLO_CYCLES;  // = 16384

struct MellotronTables {
    float data[static_cast<int>(MellotronTape::COUNT)][MELLO_TABLE_SIZE] = {};

    void build() noexcept {
        // Simple deterministic LCG for per-cycle variation
        auto lcg = [](uint32_t& s) -> float {
            s = s * 1664525u + 1013904223u;
            return static_cast<float>(s >> 16) / 65535.0f;  // 0..1
        };

        const int N = MELLO_CYCLE_SIZE;

        // ── Strings: detuned saws (3 layers ±5 cents) ─────
        {
            float* t = data[static_cast<int>(MellotronTape::Strings)];
            uint32_t rng = 0xDEAD0001u;
            for (int cyc = 0; cyc < MELLO_CYCLES; ++cyc) {
                const int off = cyc * N;
                for (int i = 0; i < N; ++i) {
                    const float ph = TWO_PI * i / N;
                    float v = 0.0f;
                    for (int h = 1; h <= 16; ++h) {
                        // Per-cycle amplitude jitter ±12%
                        const float jA = 1.0f + 0.12f * (lcg(rng) * 2.0f - 1.0f);
                        const float jP = lcg(rng) * 0.05f;  // phase drift
                        v += jA * std::sin(h * ph + jP) / h;
                        v += 0.6f * jA * std::sin(h * ph * 1.00289f + jP) / h;
                        v += 0.6f * jA * std::sin(h * ph * 0.99711f + jP) / h;
                    }
                    t[off + i] = v / 2.2f;
                }
            }
        }
        // ── Choir: formant vowel "aah" approximation ──────
        {
            float* t = data[static_cast<int>(MellotronTape::Choir)];
            uint32_t rng = 0xDEAD0002u;
            static const float baseAmps[6] = {1.0f, 0.6f, 0.8f, 0.7f, 0.5f, 0.2f};
            for (int cyc = 0; cyc < MELLO_CYCLES; ++cyc) {
                const int off = cyc * N;
                for (int i = 0; i < N; ++i) {
                    const float ph = TWO_PI * i / N;
                    float v = 0.0f;
                    for (int h = 0; h < 6; ++h) {
                        const float jA = 1.0f + 0.10f * (lcg(rng) * 2.0f - 1.0f);
                        const float jP = lcg(rng) * 0.04f;
                        v += baseAmps[h] * jA * std::sin((h + 1) * ph + jP);
                    }
                    t[off + i] = v / 3.0f;
                }
            }
        }
        // ── Flute: pure sine + gentle harmonics ────────────
        {
            float* t = data[static_cast<int>(MellotronTape::Flute)];
            uint32_t rng = 0xDEAD0003u;
            static const float baseAmps[3] = {1.0f, 0.08f, 0.03f};
            for (int cyc = 0; cyc < MELLO_CYCLES; ++cyc) {
                const int off = cyc * N;
                for (int i = 0; i < N; ++i) {
                    const float ph = TWO_PI * i / N;
                    float v = 0.0f;
                    for (int h = 0; h < 3; ++h) {
                        const float jA = 1.0f + 0.08f * (lcg(rng) * 2.0f - 1.0f);
                        const float jP = lcg(rng) * 0.03f;
                        v += baseAmps[h] * jA * std::sin((h + 1) * ph + jP);
                    }
                    t[off + i] = v;
                }
            }
        }
        // ── Brass: bright sawtooth (odd + even harmonics) ─
        {
            float* t = data[static_cast<int>(MellotronTape::Brass)];
            uint32_t rng = 0xDEAD0004u;
            for (int cyc = 0; cyc < MELLO_CYCLES; ++cyc) {
                const int off = cyc * N;
                for (int i = 0; i < N; ++i) {
                    const float ph = TWO_PI * i / N;
                    float v = 0.0f;
                    for (int h = 1; h <= 20; ++h) {
                        const float amp = 1.0f / h;
                        const float boost = (h % 2 == 1) ? 1.4f : 1.0f;
                        const float jA = 1.0f + 0.12f * (lcg(rng) * 2.0f - 1.0f);
                        const float jP = lcg(rng) * 0.05f;
                        v += amp * boost * jA * std::sin(h * ph + jP);
                    }
                    t[off + i] = v / 3.5f;
                }
            }
        }
    }

    // Linear interpolated lookup (multi-cycle table)
    float read(MellotronTape tape, float phase) const noexcept {
        const int ti  = static_cast<int>(tape);
        const float p = phase * MELLO_TABLE_SIZE;
        const int   i0 = static_cast<int>(p) & (MELLO_TABLE_SIZE - 1);
        const int   i1 = (i0 + 1) & (MELLO_TABLE_SIZE - 1);
        const float fr = p - static_cast<float>(static_cast<int>(p));
        return data[ti][i0] + fr * (data[ti][i1] - data[ti][i0]);
    }
};

// Global table — built once by MellotronEngine::init()
extern MellotronTables g_MelloTables;
